// The about section of the landing, in Kjel's words, one line per entry.
// The board stamps them in the 5x7 face: A-Z 0-9 . , ' - & ! ? / : only.
export const ABOUT_LINES = [
  "MY NAME IS KJEL - THE J IS SILENT.",
  "I AM 27 YEARS OLD, LIVING IN BROOKLYN.",
  "I WORK IN TECH SALES, STRADDLING GO-TO-MARKET ENGINEERING AND EXECUTION / BUSINESS DEVELOPMENT.",
  "IN MY FREE TIME, I REALLY ENJOY BOARD GAMES WITH MY FRIENDS, TINKERING AND WORKING ON THE GIVEN FIXATION OR PROJECT, READING, PLAYING VIDEOGAMES - REALLY INTO RUNESCAPE AND DEADLOCK RIGHT NOW.",
  "I LIKE MY FIXED GEAR BICYCLE.",
];
